In [30]:
import numpy as np
a = np.arange(10, 30).reshape(4, 5)
yellow = a[0:1, 0]
light_blue = a[:,1::2]
red = a[0, 1:4]
green = a[0:3, 2]
dark_blue = a[0::2, 4::2]
print(a,'\n')
print('yellow:',yellow,'\nligth_blue:\n',light_blue,'\nred:\n',red,'\ngreen:',green, '\ndark_blue:\n', dark_blue)

[[10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]] 

yellow: [10] 
ligth_blue:
 [[11 13]
 [16 18]
 [21 23]
 [26 28]] 
red:
 [11 12 13] 
green: [12 17 22] 
dark_blue:
 [[14]
 [24]]


In [33]:
a = np.arange(0, 27).reshape((3, 3, 3))
print('12, 13, 14: \n',a[1,1,:],'\n---------')
print('3, 12, 21: \n',a[:,1,0],'\n---------')
print('2, 5, 8: \n',a[0,:,2],'\n---------')

12, 13, 14: 
 [12 13 14] 
---------
3, 12, 21: 
 [ 3 12 21] 
---------
2, 5, 8: 
 [2 5 8] 
---------


In [40]:
filename = '../files/befkbhalderstatkode.csv'
dd = np.genfromtxt(filename, delimiter=',', dtype=np.uint, skip_header=1)


In [42]:
# How many german children were 0 years old in 2015?
mask = (dd[:,0] == 2015) & (dd[:,2] == 0) & (dd[:,3] == 5180)
print(dd[mask])
np.sum(dd[mask][:,4])

[[2015    1    0 5180    3]
 [2015    2    0 5180    5]
 [2015    3    0 5180    7]
 [2015    4    0 5180    1]
 [2015    5    0 5180    1]
 [2015    6    0 5180    2]
 [2015    8    0 5180    2]
 [2015    9    0 5180    6]
 [2015   10    0 5180    8]]


35

In [51]:
# create a function that can take any combination of the 4 parameters:AAR,BYDEL,ALDER,STATKODE and return population data
def population_data(aar, bydel, alder, statkode):
    pass